# NumPy: Python’s vectorization solution

## Motivating examples

In [4]:
distances = [10, 15, 17, 26, 20]
times = [0.3, 0.47, 0.55, 1.20, 1.0]

In [5]:
# Calculate speeds with Python
speeds = []
for i in range(len(distances)):
    speeds.append(distances[i]/times[i])
    
speeds

[33.333333333333336,
 31.914893617021278,
 30.909090909090907,
 21.666666666666668,
 20.0]

In [6]:
speeds = [d/t for d,t in zip(distances, times)]
speeds

[33.333333333333336,
 31.914893617021278,
 30.909090909090907,
 21.666666666666668,
 20.0]

In [7]:
product_quantities = [13, 5, 6, 10, 11]
prices = [1.2, 6.5, 1.0, 4.8, 5.0]
total = sum([q*p for q,p in zip(product_quantities, prices)])
total

157.1

In [ ]:
speeds = distances/times
total = sum(product_quantities*prices)

# NumPy arrays: creation, methods and attributes

## What is a NumPy array?

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is the *rank* or *dimension*.

## Creating arrays: from lists and using built-in functions

In [8]:
import numpy as np

In [9]:
# arrays from lists
distances = [10, 15, 17, 26, 20]
times = [0.3, 0.47, 0.55, 1.20, 1.0]
distances = np.array(distances)
times = np.array(times)

In [10]:
product_quantities = [13, 5, 6, 10, 11]
prices = [1.2, 6.5, 1.0, 4.8, 5.0]
product_quantities = np.array(product_quantities)
prices = np.array(prices)

In [11]:
distances

array([10, 15, 17, 26, 20])

In [12]:
type(distances)

numpy.ndarray

In [13]:
speeds = distances/times
speeds

array([ 33.33333333,  31.91489362,  30.90909091,  21.66666667,  20.        ])

In [14]:
total = sum(product_quantities*prices)
total

157.09999999999999

In [15]:
for d,t,v in zip(distances, times, speeds):
    print("{} / {} = {}".format(d,t,v))

10 / 0.3 = 33.333333333333336
15 / 0.47 = 31.914893617021278
17 / 0.55 = 30.909090909090907
26 / 1.2 = 21.666666666666668
20 / 1.0 = 20.0


### Array creation

If we pass np.array() a list of lists, it will create a 2-dimensional array. If pass a list of lists of lists, it will create a 3-dimensional array, and so on and so forth.

In [16]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [17]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Create a 3x5 floating-point array filled with ones
np.ones(shape=(3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [19]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(start=0, stop=20, step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# Create an array of 20 values evenly spaced between 0 and 1
np.linspace(0, 1, 20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

### Mathematical functions

In [21]:
x = np.linspace(-1, 1, 21)
print(np.sin(x), "\n")
print(np.exp(x), "\n")
print(x**2, "\n")

[-0.84147098 -0.78332691 -0.71735609 -0.64421769 -0.56464247 -0.47942554
 -0.38941834 -0.29552021 -0.19866933 -0.09983342  0.          0.09983342
  0.19866933  0.29552021  0.38941834  0.47942554  0.56464247  0.64421769
  0.71735609  0.78332691  0.84147098] 

[ 0.36787944  0.40656966  0.44932896  0.4965853   0.54881164  0.60653066
  0.67032005  0.74081822  0.81873075  0.90483742  1.          1.10517092
  1.22140276  1.34985881  1.4918247   1.64872127  1.8221188   2.01375271
  2.22554093  2.45960311  2.71828183] 

[ 1.    0.81  0.64  0.49  0.36  0.25  0.16  0.09  0.04  0.01  0.    0.01
  0.04  0.09  0.16  0.25  0.36  0.49  0.64  0.81  1.  ] 



### Statistical functions

In [22]:
print("Mean: ", np.mean(x))
print("Standard Deviation: ", np.std(x))
print("25th percentile: ", np.percentile(x,q=0.25))

Mean:  4.22942104619e-17
Standard Deviation:  0.605530070819
25th percentile:  -0.995
